# Load TLS certificates from Azure Key Vault into ingress controllers.

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
  namespace: ingress
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: your-keyvault-object
      key: tls.key
    - objectName: your-keyvault-object
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: nnn
    keyvaultName: my_key_vault
    objects: |
      array:
        - |
          objectName: your-keyvault-object
          objectType: secret
    tenantId: nnn
