
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld-four
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld-four
  template:
    metadata:
      labels:
        app: aks-helloworld-four
    spec:
      containers:
      - name: aks-helloworld-four
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "App4 - Default landing"
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-four
  namespace: demo
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-helloworld-four
